### ISSUE TITLE
Edit/Delete buttons misaligned in Omeka browse view in Firefox

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#10]
In the native-Omeka Neatline exhibit browser view, the "Edit" and "Delete" buttons clear so that they are vertically stacked on top of one another in Firefox. They should be side-by-side, as they are in Chrome and Safari.

**Comment by waynegraham** [comment]
Is this still open?

**Comment by davidmcclure** [comment]
Fixed.
