### ISSUE TITLE
Error in data controller test suite

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#100]
The testOpenlayers() test in the DataControllerTest throws an error when the code tries to hit the ->findByItem() method on the NeatlineMapsService table. The method actually works fine. I think this could be some kind of bug in the testing environment, either in our code or in Omeka/phpunit, that doesn't like the pattern of invoking table class A from inside of table class B.

**Comment by erochest** [comment]
The tests all pass for me. I did need to make some changes to get the tests to run at all. Those changes are here 1651ea3f041b930e81f4faa7d6caa5c8bdaf84db.

**Comment by davidmcclure** [comment]
Fixed.
