### ISSUE TITLE
Strange timezone displacement on timeline

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#102]
There is some kind of strange interaction going on with the "timezones" options in Simile. By default, before I made any direct configuration changes in the code that instantiates the timeline, I consistently see all time points/spans rendered 4 hours "ahead" of where they should be. So, if I set a time point at January 1, 2012 at midnight, the point gets rendered at ~4AM. I was able to fix this by manually clobber this by setting timeZone: -4 in the band constructor.

Why is this happening? Is Simile somehow getting a timezone information from the browser when it spins up? Will the magic constant here make the rendering incorrect for people in different timezones?

**Comment by phybernightmare** [comment]
Take a look at the UTC timestamps; see if this is in GMT

**Comment by waynegraham** [comment]
@clioweb Can you check this out since you're on the west coast now?

**Comment by erochest** [comment]
This may be a lead http://www.simile-widgets.org/wiki/SimileAjax/DateTime

**Comment by jeremyboggs** [comment]
it might help to save the time output for this using Zend_Date. You can check out how I do it on [Neatline Time](https://github.com/scholarslab/NeatlineTime/blob/develop/helpers/NeatlineTimeFunctions.php#L464).

**Comment by davidmcclure** [comment]
Fixed by fe2d027b26a3b7e559fe974847fdc8698d72d659.
