### ISSUE TITLE
Timeline "snapping" after viewport resize

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#103]
Sometimes, after the timeline viewport is vertically resized, Simile starts to "snap" after the timeline is dragged - the horizontal scroll position reverts back to the previous position. To replicate:
- Zoom pretty far in on the timeline, to the day/hour unit.
- Drag the timeline height upwards.
- Try to scroll the timeline right or left. Sometimes (but not always), the timeline will immediately revert back to the old scroll position as soon as the drag is ended.

This only happens when the timeline is zoomed far in. When you zoom back out, you can see a very small snap, but the scroll position stays more or less the same. It's as if there's some time-interval threshold under which Simile won't "persist" the drag that is hard to achieve when the frame is zoomed really far in.

Maybe my custom zooming widget isn't updating some sort of scaling parameter?

**Comment by waynegraham** [comment]
Bump this to post release
