### ISSUE TITLE
Erratically jumpy mousewheel zoom on map

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#104]
Periodically, something goes wrong and the mousewheel zoom becomes massively oversensitive - a single click on the wheel will go from a scale of a couple miles back up to the entire world. I've seen this happen on multiple mouses, so it's not a device issue. This usually doesn't happen, but it crops up pretty regularly. I can't figure out how to reliably replicate it.

Not sure if this is NL or OL. I fear the latter.

**Comment by erochest** [comment]
It looks like this is related to analog scrolling devices and OL.

https://github.com/openlayers/openlayers/pull/483

This hasn't been merged yet. I'll update OL again when (if) it is.
