### ISSUE TITLE
Find a good custom scrolling solution for full-height bubbles

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#105]
Currently, the full-height pop up bubbles use browser-default scrolling. This is unsightly, and the situation really calls for a more compact, Lion-style scrollbar. Custom scrollbars are hard to write well, and I'd rather use something existing if possible.

Anyone recognize the widget that's being used on the Raphael documentation (http://raphaeljs.com/reference.html)?

**Comment by jeremyboggs** [comment]
> Anyone recognize the widget that's being used on the Raphael documentation (http://raphaeljs.com/reference.html)?

Looks like they're just using the `::-webkit-scrollbar` pseudoclass to style those. There may be other vendor prefixed ways to style the scrollbar.

There's also the [slider in jQuery UI](http://jqueryui.com/demos/slider/#side-scroll).

**Comment by davidmcclure** [comment]
Done.
