### ISSUE TITLE
Close open bubble when the cursor leaves the exhibit container 

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#106]
When there is a map vector that is partially occluded by the edge fo the exhibit container, the popup bubble inappropriately will "stick" if the cursor leaves the exhibit container without first leaving the vector, which would normally trigger the bubble hide event.

The bubbles widget should bind a listener onto its this.element that automatically closes an open bubble on mouseleave.

**Comment by erochest** [comment]
Closed in 238f92297bff9ff555963fbc500e0897c1a38601, contrary to the commit logs.
