### ISSUE TITLE
Redesign the public-facing exhibit views

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#109]
Currently, there are 3 public-facing exhibit views: "in-theme" (the exhibit is instantiated directly inside of the default site theme, without any kind of modifications to the surrounding structure), "fullscreen" (the exhibit occupies the whole screen except for a thin bar across the top with the Neatline logo and the exhibit title), and "embed" (the same as fullscreen, but without the bar; designed for doing embedded iframes).

These are confusing, and none of them really does the trick. What's needed is a single, attractive public-facing show page for the exhibits that does these things:
- Devotes most of the screen real estate to the exhibit.
- Shows the title of the exhibit and the Neatline logo.
- Shows a short piece of descriptive text that provides a high-level overview of what the user is seeing.

For example, I really like the layout of this: http://mapbox.com/map-sites/dc-properties/. From a data standpoint, all of the pieces of the puzzle are in place to do this - I added a general-purpose "description" field to the exhibit model that the user can fill out during the exhibit add/edit workflow.

I think this is extremely important. There needs to be a really attractive, out-of-the-box presentation for exhibits. When I randomly run across a project on the internet, this is the main criteria on which I judge it.

**Comment by jeremyboggs** [comment]
Agreed about having one attractive public-facing show page for the exhibits. I think the fullscreen one is right for this, too.

It would probably be better to move the fullscreen as the default for the showAction, then just add a response context for the show route for 'embed', to get an embeddable version. like `neatline-exhibits/show/1?output=embed`

Seems like this might be related to issue #112, about the linkToNeatline helper, that I posted earlier.

**Comment by davidmcclure** [comment]
Yep, I really like the idea of one route, multiple outputs.

**Comment by jeremyboggs** [comment]
OK, that's easy enough to do. That will involve, I believe, getting rid of the PublicController and moving that stuff instead to the IndexController, and adding some outputs to the response. We could even do the in-theme view as one of the outputs.

**Comment by davidmcclure** [comment]
I wonder if it makes more sense to rename IndexController to AdminController (which is what it actually is, as it currently exists), and just change the name of the PublicController to IndexController.

I don't really know why I got in the habit of using "index" for the Omeka admin - it doesn't make any sense.

**Comment by jeremyboggs** [comment]
There isn't really a need to have a separate admin and index controller. We could just merge those two, and make sure the all the actions are accessed through the ACL.

**Comment by jeremyboggs** [comment]
[This commit](https://github.com/scholarslab/Neatline/commit/0337510e913c9dc17c22a84b0876d6e68c05ee38) is confusing to me. Is there a reason we need both a show and fullscreen view for exhibits? Seems like we agreed to have the show view be fullscreen. If so, we should merge those into the show view and go with that.

**Comment by jeremyboggs** [comment]
Forget my last comment, I remember talking about that change now.
