### ISSUE TITLE
Editor navigation wraps into map area on smaller windows

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#115]
If the browser window is narrow enough, the editor's settings navigation wraps below the header, making them harder to read.

We should either set a minimum width on the body for the editor, or add some responsive styles to accommodate smaller windows.

**Comment by davidmcclure** [comment]
Yeah, this always bites me when I show NL on projectors, and it's a big UX problem for people on small screens.

Could we just start shrinking down the text size on the drop-down tab labels as the resolution drops?

**Comment by jeremyboggs** [comment]
@davidmcclure 

> Could we just start shrinking down the text size on the drop-down tab labels as the resolution drops?

Yeah, or we could just fix the width, which would generate a horizontal scroll at a certain screen width. I think this would be far better than it jumping down onto the map.

Either would require some CSS with media queries. It might be worth extending this ticket to make the Neatline editor and public display more workable with a variety of viewport sizes.

**Comment by jeremyboggs** [comment]
Thsi also happens if you have a fairly long title for your exhibit.

**Comment by jeremyboggs** [comment]
Given how this navigation also looks when a non-English translation is active in Omeka, I'd recommend separating the header into two bars:
- First: Logo, Title of Exhibit, Back to Omeka
- Second: Neatline editor navigation.

We'd still likely need to add styles to ensure the navigation links don't wrap into the map area. This could be prevented by not specifying a fixed height for either bar.

**Comment by erochest** [comment]
This may be happening again, if `cooper.lib.virginia.edu` is running master.

I just verified that it is still happening on `cooper.lib` after updating the code. See the sample Neatline for an example.

**Comment by jeremyboggs** [comment]
I think the best solution for this would be to get rid of that list of navigation elements entirely, and instead put configuration links on each of the Neatline panels. That way, if someone wants to hide that particular part of the Neatline editor, the configuration button would be hidden with it. I also think it would make a clearer association between the button and that section of the editor.

**Comment by erochest** [comment]
I like that, but I wonder where the layout editor would go. Would that stay where it is now?

**Comment by jeremyboggs** [comment]
Yeah, I would keep that where it is now, unless we could think of a better place. Might be worth exploring.

**Comment by davidmcclure** [comment]
Fixed in 1.2.
