### ISSUE TITLE
When a new map feature is added to a new record, it is invisible until after the record is saved

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#117]
After you add a new exhibit record, there's a bug that causes any new map features to be totally invisible until after the record is saved. To replicate:
- In an exhibit, add a new record.
- Save the record.
- Now, add a polygon to the map. When you double-click to close the shape, it will disappear on the map.
- Click save again. The feature is saved appropriately, and is now stable in the exhibit.

There's no problem from a data standpoint - but this is really problematic from the user's perspective, since it appears that the vector totally disappears after it has been drawn.

**Comment by erochest** [comment]
Part of this fix involved having the map turned on by default for new Neatline data records. Whether this is desirable is debatable, but we'll need more changes on the workflow to get around this.
