### ISSUE TITLE
Feature not reselected after mouseout and mouseover

### ISSUE THREAD

**Issue by erochest** [scholarslab/Neatline#118]
To reproduce:
1. Hover over a feature to select it;
2. Move off the map; the feature is unselected;
3. Move back over the map over the feature; the feature is not re-selected.

The feature should be re-selected when you move back over the map+feature.

**Comment by davidmcclure** [comment]
I fear that this is essentially un-fixable. My understanding is that OL just triggers the feature enter/exit callback when the cursor traverses the _boundary_ of a vector - so, when the cursor reappears in the middle of the feature when it crosses back into the map (but without crossing a border), I don't think OL has any knowledge of what's going on.

**Comment by erochest** [comment]
The only weird thing is that it does reselect the feature, if your cursor leaves the map when it's not over a feature. Kind of hard to explain. Maybe I need to do a screencast.

My guess is that we're going to have to dig into the dirty internals of the OL state and event handling.

I'll probably let this sit and revisit it later.

**Comment by erochest** [comment]
The behavior of the widget has changed. Now the featured is not unselected at number 2 in the steps to reproduce above. Instead, it's unselected when you move back over the map outside the feature. Or it remains selected when you move back over the map over the feature.

This behavior appears to be correct.
