### ISSUE TITLE
Neatline slugs should be unique

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#119]
You can currently add two separate Neatline exhibits with the same slug. We should either prevent people from saving an exhibit with an existing slug, or save the exhibit and append an integer to the slug.

'slug' shoudl probably also be a unique field in the neatline_exhibits table.

**Comment by davidmcclure** [comment]
Hm, I can't reproduce this. Duplicate slugs are blocked (https://github.com/scholarslab/Neatline/blob/feature/items/forms/AddExhibitForm.php#L94), and this is pretty thoroughly tested (https://github.com/scholarslab/Neatline/blob/master/tests/integration/IndexControllerTest.php#L387).

Was there anything out of the ordinary about the workflow that caused the bug? I just tried to add a duplicate slug, and it blocked it appropriately.

**Comment by jeremyboggs** [comment]
Closing as invalid. Bug with local code. Thought I had switched over to the dev branch to confirm before posting, but just checked the dev branch and also can't reproduce.
