### ISSUE TITLE
Clear the WMS when user deletes an attached geotiff

### ISSUE THREAD

**Issue by nowviskie** [scholarslab/Neatline#121]
If possible, deleting a geotiff attached to an Omeka item should also clear out the WMS layer its upload created. (Very low priority.)

**Comment by nowviskie** [comment]
... or contemplate whether NeatlineMaps users really care about having the tiff attached to their Omeka item at all!  Do they mainly feel like they're uploading the tiff to Geoserver? If so, we probably only want to save the WMS notations and drive people to delete those if they want to clear them out.  This would be better in cases where users want to attach un-warped viewing images to a record that also has a geotiff/WMS.

Would have to think about implications for derivative thumbnails, though, if the first (or only) file attached is the geotiff.

**Comment by waynegraham** [comment]
Is this a Neatline or NeatlineMaps issue?

**Comment by davidmcclure** [comment]
NeatlineMaps. I'm closing this issues and moving both of nowviskie's comments to a ticket on NeatlineMaps.

https://github.com/scholarslab/NeatlineMaps/issues/48
