### ISSUE TITLE
Extremely sluggish "refresh" animation in FF

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#126]
In Firefox, the exhibit refresh effect that is displayed after a successful configuration change (the white flash on the exhibit container) causes the .js frame rate on the page to drop dramatically for a few seconds. I believe that this code is tweening opacity, which can cause problems if it's not done correctly.

**Comment by erochest** [comment]
The refresh animation for FF is slower than in Chrome. But if anything, Chrome's a little too fast.

This could have been an issue with the computer at the moment, or with the specific version of FF, and since FF has moved to automatic updates, that'll be less of an issue.
