### ISSUE TITLE
Activating a different record while drawing a map annotation makes it impossible to commit the feature

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#127]
To replicate:
- Create a record with a vector annotation.
- Create another record, and start to draw out a vector annotation.
- While you draw, click on the vector for the other item.

This causes the other item to get selected, which confuses the maps widget, since the current, unclosed vector shape was initiated on the vector layer for the second record, but the layer for the first record has been activated by the click. When this happens, it is impossible to "close" out the vector, and the only solution is to refresh the page and lose the vector data of the unclosed shape.

**Comment by waynegraham** [comment]
If a feature is being drawn, disable default behavior.
