### ISSUE TITLE
Fast mouse movements to the right cause bubbles to close prematurely

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#128]
To replicate:
- Create a record with a large polygon map vector.
- In the public view (with the bubbles activated), move the mouse quickly onto the vector from the left side of the screen moving towards the right side.

When the mouse is moving (even moderately) fast, the cursor will slip on top of the SVG vector that forms the connector triangle, which trips the feature-leave even in Openlayers, which in turn causes the bubble to close. The bubble will not become visible again unless the user moves the cursor off the vector and then back on.

**Comment by waynegraham** [comment]
Not a blocker...

**Comment by davidmcclure** [comment]
Fixed by ceb436a28f16f944bf02fc58aefb564946682cf1.
