### ISSUE TITLE
Occasionally, closing a record edit form does not cause the rest of the record listings to reappear

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#129]
This bug is erratic and I can't reliably replicate it, but it crops up pretty regularly. This is what _should_ happen when you edit a record:
- Click on the listing for the record in the browser tray.
- The record opens, filling the entire browser tray.
- To close the record, click on the "Close Record" button at the bottom of the form, or click on the title of the record at the top of the form.
- This should cause the form to contract, and make the rest of the list reappear.

Sometimes, though, the list does not reappear. The form always closes, but periodically the title of the form that was just being edited gets marooned in the tray, and none of the other records reappear.

You can usually fix this by just clicking on the marooned title again.

**Comment by waynegraham** [comment]
There are two functions that show/hide and it may be something that gets confused under certain circumstances.

**Comment by davidmcclure** [comment]
Fixed.
