### ISSUE TITLE
Add Permalink Control

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#131]
It may be nice to include the permalink control on the map so users can "bookmark" a particular view

**Comment by waynegraham** [comment]
http://dev.openlayers.org/docs/files/OpenLayers/Control/Permalink-js.html

**Comment by jeremyboggs** [comment]
+1 for this.

**Comment by davidmcclure** [comment]
This is accomplished by the record hard-linking in 2.3.
