### ISSUE TITLE
"null" strings getting saved as default_focus_date

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#136]
There is a bug that cases the string "null" to get saved as the value for default_focus_date on the NeatlineExhibit model. This in turn causes the setStartingVisibility method on the maps widget to think that there is a set value and attempt to filter the vector layers based on the "null" string, which cases nothing to be rendered since nothing evaluates as being before or after the non-date.

I suspect that there is a problem is somewhere in the flow that occurs after the user clicks the "Save Starting Viewport Positions" in the editor. This gets handled by the positionsAction() in the editor controller, which in turn calls out to the saveViewportPositions() method on the exhibit model.

**Comment by erochest** [comment]
I can't reproduce this. I'll protect `default_focus_date` from getting set to `'null'`. Let me know and re-open this issue if this re-appears.
