### ISSUE TITLE
When a bubble is frozen, clicking on another feature does not open the new bubble

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#143]
To replicate:
- Click on a feature to freeze the bubble.
- Without closing the bubble, click on a different feature.

The first bubble closes, but the bubble for the second feature does not display. Things get even more confusing for the user, since the second click selects the second feature, meaning that the feature then has to be deselected before it can be clicked on again, at which point the bubble finally displays.

**Comment by waynegraham** [comment]
this also occurs when clicking on the same polygon; selection activates, but box does not appear
