### ISSUE TITLE
unable to remove item from tray

### ISSUE THREAD

**Issue by nowviskie** [scholarslab/Neatline#146]
I have an item that got "stuck" in the item tray after I tried to remove it. It's a ghost record -- it won't open on click and is no longer controlling the map.  If I re-add the item with the check-box, I get another (functional) one.  Removing it again only removes the good one, not the ghost.  See South Carolina in this exhibit: http://henshaw.scholarslab.org/neatline-exhibits/show/geodetic-texts

(Not something to explore before this week's launch.)

**Comment by erochest** [comment]
Well, it obviously happened: I can see it on the link above.

This appears to be a data integrity problem, but reproducing it will very difficult. At this point, it's hard to say exactly what version of the code the server was running when it happened (or if it was being actively upgraded as the item was created).

I'll not close this, but I will remove it from this milestone.
