### ISSUE TITLE
Items/Map/Timeline boxes misplaced on WebKit

### ISSUE THREAD

**Issue by pleonard212** [scholarslab/Neatline#147]
Firefox 13.0.1 renders these sets of controls correctly:

![Firefox](http://home.uchicago.edu/psleonar/dev/neatlinebugs/firefox.png)

...but WebKit browsers such as Safari 5.1.7 and Chrome 20.0.1132.47 squish all the checkboxes together:

![Safari](http://home.uchicago.edu/psleonar/dev/neatlinebugs/safari.png)

(all on OS X 10.7.4)

**Comment by jeremyboggs** [comment]
Confirmed this happens in Safari 5.1.7, though not Chrome **20.0.1132.57**, on OS X 10.6.8. Curious if this still happens if you update Chrome. Regardless, this is something we'll fix.
