### ISSUE TITLE
this.modifyFeatures is undefined

### ISSUE THREAD

**Issue by pleonard212** [scholarslab/Neatline#150]
So occasionally I am getting this error, invoked from map_editor.js on line 9.  It seems to happen most recently when I try to add an (imported from Omeka) item into the sidebar, although I think it's also happened to me in the past when trying to set geographic points.

Let me know what I can do in regards to FireBug or other debuggers to expose any contexts or logs, and I'll post them as best I can...
thanks!

**Comment by erochest** [comment]
I haven't been able to reproduce this, but I went ahead and hardened the code in `map_editor.js` against `modifyFeatures` not being set.
