### ISSUE TITLE
Possible to set an illegal zoom level in Google Physical

### ISSUE THREAD

**Issue by pleonard212** [scholarslab/Neatline#151]
So Google Physical (aka Terrain) doesn't support as many zoom levels as other types of maps.  But if you use the Base Layer sector on the right-hand side of the map (the icon 3 stacked white sheets on a black background) you can switch to Satellite mode and then zoom in past what Terrain can support. If you then choose Fix Starting Viewpoint Positions, the result will be a map the zooms WAY out when viewed, because it's trying to apply zoom level 17 to a Terrain map.

What people should do instead, of course, is use the Map Settings menu to switch the Default Base Layer.  But that's easy to forget to do because we're used to using the icon on the right.

I don't think it makes sense to disable the right-hand icon, because it's important to toggle between different views when figuring out where stuff should be be on the map. But kind of feels like the Default Base Layer and Fix Starting Viewpoint Positions should live in the same panel -- then the user would think about them as part of the same process.  Right now, they're split between Map Settings and Layout Editor. And perhaps at least expose the current zoom layer as a number, so that the user can see if its illegal in the current base map?

**Comment by davidmcclure** [comment]
Yep, I've had this happen to me too. Another solution would be to just get rid of the dropdown select in the "Map Settings" altogether, and make it so that when you hit "Fix Starting Viewport Positions" the currently selected base layer is saved as the default.

**Comment by pleonard212** [comment]
That idea (Fix Starting Viewport Positions inheriting current layer) is a great one, and I think more closely matches user expectations (They change map to the right base layer, adjust the zoom, and then hit Save, which freezes everything in place).

**Comment by davidmcclure** [comment]
Implemented in 2c10dc2bb649e127428252642219babac42507cc.
