### ISSUE TITLE
Neatline in Omeka, Zend error

### ISSUE THREAD

**Issue by jwernimo** [scholarslab/Neatline#153]
Hello,

I've installed Neatline as per the instructions for an Omeka plugin. The whole process went smoothly, all the way to the install interface in Omeka. But when I click on the Neatline tab, what opens is a page with the following error:

Catchable fatal error: Object of class User could not be converted to string in /home/jwernimo/countingthedead.org/plaguecms/application/libraries/Zend/Acl/Role/Registry.php on line 124

Some quick searching suggests this is a php 5.2 related error and I'm too green to know how to execute a fix. 

Ideas?

Thanks,
Jacque

**Comment by waynegraham** [comment]
Jaque, which version of Omeka are you working with? 1.5.1? 

Also, which patch version of PHP; I believe the latest is 5.2.17.

**Comment by jwernimo** [comment]
Hi Wayne,

I'm using the one-click install that was avail in dreamhost - which is 1.3.2. I believe that I'm using a PHP 5.2, but need to log on to the server to get the specific one. I'm in Germany right now and the wifi here is pretty slow - I'll see what I can do.

Thanks,
Jacque

**Comment by waynegraham** [comment]
Hi Jaque,

Let me run this one down; you may need to upgrade your version of Omeka to the latest (1.5.2). You can check out documentation at (http://omeka.org/codex/Upgrading).

Wayne

**Comment by jwernimo** [comment]
Hi Wayne,

Just thought I'd follow up to see if there's any new information on this?

Thanks,
Jacque

**Comment by waynegraham** [comment]
Have you been able to upgrade? Basically there are some incompatibilities with old versions of Omeka. The "fix" for this is to restrict this plugin to the 1.5.x branch (and 2.0 when that comes out) as the underlying APIs have changed quite a bit...

**Comment by erochest** [comment]
`omeka_minimum_version` has been set to "1.5".
