### ISSUE TITLE
"Edit Query" form not visible in Omeka 1.5.2

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#154]
In Omeka 1.5.2, the "Edit Query" forms for Neatline exhibits just display an empty container div. Advanced search in 1.5.2 also appears to be broken - I get a 500 when I click on "Advanced Search" in the item browse view. This could be the root problem.

**Comment by jeremyboggs** [comment]
This is a bug in Omeka 1.5.2, which I actually introduced and got merged. Suspect they'll release 1.5.3 very soon.

**Comment by jeremyboggs** [comment]
Closed since [Omeka 1.5.3](http://omeka.org/codex/Release_Notes_for_1.5.3) fixes this issue.
