### ISSUE TITLE
Add ACL check for Contributor users

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#159]
We should add ACL permissions checks to ensure Contributor-level users can browse/show/edit/delete all public Neatlines or Neatlines they've created.

**Comment by jeremyboggs** [comment]
Suggest we put this off until we refactor Neatlien for Omeka 2.0, since it includes a shared ownership assertion class that we can use for checking ownership on Neatline records.

**Comment by davidmcclure** [comment]
Closing this for now, since it's really part of the larger conversation about how to organize the ACL to make it possible to so "multi-site" Neatline installations inside of a single Omeka install.

**Comment by jeremyboggs** [comment]
> Closing this for now, since it's really part of the larger conversation about how to organize the ACL to make it possible to so "multi-site" Neatline installations inside of a single Omeka install.

@davidmcclure So did you do this, or are we just not going to do it? If the latter, I'd suggest keeping the ticket open, bumping the priority down or remove a priority indicator.

**Comment by davidmcclure** [comment]
No, it's not done, just cleaning up and consolidating tickets. We should talk about this and re-post in more general form that captures the breadth of the task.
