### ISSUE TITLE
Add smallscroll() bars to timeline popups

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#17]
Right now, the timeline popups are fairly small. Since these could conceivably used to present fairly in-depth and lengthy interpretive / descriptive prose, they should be able to accomodate larger amounts of text.

If the auto height of the boxes is above a certain constant (say, 400px), smallscroll() the content divs.

**Comment by waynegraham** [comment]
overflow scroll-y for now

**Comment by davidmcclure** [comment]
No longer relevant.
