### ISSUE TITLE
add a map key option

### ISSUE THREAD

**Issue by ghost** [scholarslab/Neatline#172]
It would be helpful to be able to add a map key. All the arrows, shapes, etc. would make more sense.

**Comment by waynegraham** [comment]
You should be able to _kind_ of do this by adding the "key" as an item. It's not a more traditional map key, but if you're really getting in to that kind of mapping, it may be better to be pulling that information off a real gis server (like geoserver) with the NeatlineMaps plugin.

**Comment by davidmcclure** [comment]
@egnally, Do you mean a key for the custom vectors (points/lines/shapes) that are added by the user in an exhibit? That's actually kind of an interestingly difficult task to work directly into OpenLayers without a core modification. Really, I wonder if it would be easiest / cleanest to do this at the level of the theme, just with a static image?

**Comment by ghost** [comment]
That is what I had in mind. A static image would get the job done. But it might be nice to have a key that can do some work, meaning, a key that could show/hide certain vectors as if they were layers. This would help to illustrate certain visual patterns in some of the more chaotic projects.

**Comment by davidmcclure** [comment]
Closing this for now, since this is an ideal use-case for the new "widget" construct in v1.2, which makes it possible to write little plugins that inject custom user interface elements into exhibits.
