### ISSUE TITLE
Recursive parent-child relationships cause problems

### ISSUE THREAD

**Issue by mialondon** [scholarslab/Neatline#175]
I was playing with parent-child relationships and managed to make two items each others' parents.  I'm assuming this is why the Edit interface started throwing json loading errors but haven't tried to replicate it to be certain.  I resolved it by manually editing the backend to set the parent ID to null for one of the records.

**Comment by erochest** [comment]
Oops. You're right. That should not be possible.

Thanks for catching it.

**Comment by davidmcclure** [comment]
The parent-child construct is removed in v1.2, replaced by the tags/stylesheet system.
