### ISSUE TITLE
Neatline installed inside Omeka, controls on map not visible 

### ISSUE THREAD

**Issue by blyth** [scholarslab/Neatline#180]
I searched through the issues but didn't see one related to this. Apologies if I missed it. I installed Neatline in my Omeka 1.5.3 installation. When I try to set locations on the map, I cannot see the controls described and pictured in the readme file. However, when I hover above the "Drag" button, my cursor changes from an arrow to a hand, as if there is something clickable there that I just can't see.

Am I missing something?  Is there something I need to do to make these visible?

Screenshot: <img src="http://mythandart.com/images/neatline_issue.jpg">

**Comment by davidmcclure** [comment]
No, you shouldn't have to do anything - they should be visible. It this _always_ the case, or does it just happen occasionally, when the application is in certain states?

If they're always invisible, I suspect some kind of z-index collision in the css. What browser are you using?

**Comment by blyth** [comment]
This happens every time. I have removed and reinstalled Neatline, but no change. I am using Firefox 16.0.2.

**Comment by davidmcclure** [comment]
This is fixed in 1.2.
