### ISSUE TITLE
Rethink how bubble content works

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#181]
Right now the way bubble content is constructed is different depending on how the Neatline item record is saved. This makes it difficult to do things like add a filter to modify that content when displayed in an exhibit.

It would seem more consistent to use a HTML or JSON partial for this bubble content, that would actually work if you visited that partial in the browser with a URL. Then, Neatline could just call that partial via its URL with Ajax. This would make it easier to add a filter or hook for bubble content.

**Comment by jeremyboggs** [comment]
Actually this could just add a new context for the core items/show view in Omeka, similar to how Neatline Time does with adding a new JSON output just for SIMILE.

**Comment by davidmcclure** [comment]
This problem is eliminated by the item-import flow in v1.2, which moves all of the display logic into the theme templates.
