### ISSUE TITLE
Add more formatting options to Neatline description editor

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#182]
We currently only load the default options used in Omeka's instance of TinyMCE, but these formatting options are pretty limited. We should review all the possible formatting options TinyMCE provides and add any addition options that would be useful for exhibit builders.

**Comment by davidmcclure** [comment]
Actually, in the new version, there are _no_ formatting options on the exhibit "Narrative" field. We should just instantiate CKEditor on the field for consistency with the record forms.

**Comment by davidmcclure** [comment]
Implemented by 6dce776809627cdf0f3ab61f21dbfeda7530dde1.
