### ISSUE TITLE
Problems with dates BC

### ISSUE THREAD

**Issue by mptaylor** [scholarslab/Neatline#184]
Hi there,

While Neatline seems able to handle BC dates in the "Start Date" and "End Date" fields of the temporal settings for an item (it seems to parse a "-" placed before the ISO 8601 date correctly), this doesn't seem to work in "Start Visible Date" or "Start End Date" fields. If, for example, an item is set to be visible only from 490 to 489 BC, it will instead be visible from AD489 to 490. I assume that means the "Visible Dates" just aren't seeing or parsing the "-" I have in there.

Similarly, Neatline won't let me fix a starting viewport position at a BC date. While it works straightforwardly for all AD dates, if I move the timeline to a BC date and hit "Fix starting viewport positions" nothing happens.

Thanks,

Matthew

**Comment by davidmcclure** [comment]
Hey Matthew - So, after much experimentation, it appears that JavaScript actually _can_ natively parse BC dates, but you have to use a somewhat strange syntax. Just put **the negative sign, two leading zeroes, and then the full four-digit representation of the year**. For example:

1000 BC = `-001000`
99 BC = `-000099`

From there, you can cake on any level of further precision supported by the [ISO spec](http://en.wikipedia.org/wiki/ISO_8601) (months, days, etc.):

June 25, 1000 BC = `-001000-06-25`

This works with the current version of Neatline (`2.0.1`) on Chrome, Firefox, and Safari. Whodathunk.

**Comment by mptaylor** [comment]
Hi David,

Beautiful! Thank you. I look forward to checking it out for myself.

Best,

Matthew
