### ISSUE TITLE
Feature display bugs in Safari

### ISSUE THREAD

**Issue by ewg118** [scholarslab/Neatline#195]
In a live demo today, almost no features were appearing in my presentation on Lisa's Mac.  She is running Safari, but I don't know what version.  I have tested in Firefox 20.0 and Chrome 26.0.1410.63, and it works fine.

**Comment by waynegraham** [comment]
We need a little more information to reproduce the issue (couldn't immediately do it on 6.0.4)...

Was this just a random number of features? Is there a URL? What theme?

**Comment by ewg118** [comment]
I will try to get a Safari version number.  The features appeared on the timeline, but not the map.  The ones which appeared were seemingly random: both AD and BC dates, both polygons and points.

http://ibnjubayr.lib.virginia.edu/neatline-exhibits/show/urban-development-of-damascus/fullscreen

**Comment by ewg118** [comment]
Her Safari version is 5.1.9.

If Neatline works in the current version of Safari, it's probably not worth pursuing the issue much further, but for future reference, some polygonal features in other presentations weren't showing up in the older version of Safari.

**Comment by waynegraham** [comment]
5.1.9 is the latest on OS X 10.6 and 10.7; not sure if there's a webkit issue in the background. Does this problem persist? There was an issue in that particular theme that was causing some weird issues to pop up...

**Comment by davidmcclure** [comment]
This is resolved in 2.0.
