### ISSUE TITLE
Style Tab Scrolling

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#206]
On the style tab, I find myself often struggling to scroll down to click save. Could we move that save button up to the top of the screen? Maybe next to the tabs across the top so as you change context, the save button is always there? 

Maybe use the accordion as well to break that very long screen up?

**Comment by davidmcclure** [comment]
Duly agreed. Another option would be to split the fieldsets in the style tab into multiple tabs. Eg, have separate "Groups" and "Colors" tabs.

**Comment by davidmcclure** [comment]
This is fixed - now, the "Save" and "Delete" buttons are fixed at the bottom of the screen, so that they're always visible, no matter what the scroll offset of the form.
