### ISSUE TITLE
Import Items Error

### ISSUE THREAD

**Issue by coryduclos** [scholarslab/Neatline#208]
I'm running Omeka on a Bluehost server, so this may be an issue with Bluehost, but any attempt to import an item from Omeka to Neatline produces the following error:

RuntimeException
The configured PHP path (/usr/bin/php) does not point to a PHP-CLI binary.

**Comment by waynegraham** [comment]
I suspect the PHP location set in Omeka isn't correct; if you have command-line access to the server, you can find the correct path to the executable PHP with:

``` bash
$ which php
```

You may need to then edit the Omeka configuration for the `background.php.path = ""` (in `omeka/application/config/config.ini`)

**Comment by coryduclos** [comment]
The which php command gives me the same path (/usr/bin/php) and editing the config.ini results in the same error.

**Comment by coryduclos** [comment]
I think I got. I used the path /usr/bin/php-cli

**Comment by waynegraham** [comment]
Going to close this one...
