### ISSUE TITLE
Public View Full Screen

### ISSUE THREAD

**Issue by coryduclos** [scholarslab/Neatline#209]
Am I wrong that it seems like the public view no longer has a full-screen view option?

**Comment by waynegraham** [comment]
The fullscreen route has been removed from the latest version to give theme developers more control over how Neatline is implemented in the theme. If you have a strong feeling about adding it back in though, let us know.

**Comment by coryduclos** [comment]
It would be nice not to have to depend on a them developer's preferences for those of us who don't develop our own themes.

**Comment by davidmcclure** [comment]
I agree @coryduclos. This didn't make it into 2.0.0, but I'll try to get it in the next point release.

**Comment by colonusgroup** [comment]
I would also appreciate a full screen option.

**Comment by martiniusDE** [comment]
hello,

I would also appreciate the full screen option.

Maybe like this one: https://github.com/thisismattmiller/OpenLayers-Omeka-Zoom-Plugin

There is only some line of JavaScript code in the OpenLayers.js (here: https://github.com/thisismattmiller/OpenLayers-Omeka-Zoom-Plugin/blob/master/views/shared/javascripts/OpenLayersZoom.js - Line 51).

Can I put it somewhere myself?

Thanks

**Comment by davidmcclure** [comment]
Hi folks - this feature was implemented in 661d2cd352926fd6a9e75db044db83be2366ef14, and will be pushed out with version 2.0.5 later this week.
