### ISSUE TITLE
Add button to set starting position of map and timeline, default heights/widths

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#21]
There should be a button, accessible via a menu/dropdown in the topbar, that, when clicked will record the current focus and zoom settings of the map and timeline and the current height/width percentages and make them the default settings when a user hits the exhibit.

**Comment by waynegraham** [comment]
Is this just using the OpenLayers.Control.Permalink?

**Comment by davidmcclure** [comment]
Done.
