### ISSUE TITLE
Browse Neatline Exhibits on Homepage

### ISSUE THREAD

**Issue by elotroalex** [scholarslab/Neatline#211]
New users are asking to be able to browse neatline exhibits on the homepage by default.

**Comment by jeremyboggs** [comment]
Unless you mean something else, @elotroalex, this can be done in Omeka 2.0 by [choosing a homepage](http://omeka.org/codex/Managing_Navigation_2.0#Choose_a_Homepage) in Omeka's Navigation settings.

**Comment by jeremyboggs** [comment]
Actually, looks like you can't currently do this as I previously commented, since the Neatline plugin doesn't add navigation to the public navigation list.

**Comment by elotroalex** [comment]
i need to sit down and play with it more. i was specifically wondering if
we could make it so they show up on the regular lists of exhibits by
default.

**Comment by davidmcclure** [comment]
This is addressed by the new NeatLight theme, which takes over the front page with the list of exhibits.

**Comment by jeremyboggs** [comment]
Think we should still do this in the plugin sometime, @clured, since folks may want to use their own theme.

**Comment by elotroalex** [comment]
agree with Jeremy

**Comment by davidmcclure** [comment]
What's the ideal behavior? Should we just add a link to the front page (similar to the default "Browse Items," etc), or actually list out the exhibits on the front page?

**Comment by elotroalex** [comment]
a) list exhibits on the front page as neatline exhibits, or b) merge them
with the regular exhibits list

**Comment by jeremyboggs** [comment]
@davidmcclure Guess we'd need to do two things:
1. Create a neatline-exhibits/browse view that would be displayed by any theme.
2. Pass a link to that view to the public navigation hook, so it would be added to the navigation by default and would be available to folks using Omeka's Navigation builder to rename/rearrange. Would also make it available to Omeka's setting for choosing the home page.

Not sure I agree with @elotroalex's suggestion that we merge Neatline's exhibits with the ExhibitBuilder plugin's exhibits. Think that's beyond the scope of the Neatline plugin for now, but might be something we could help folks figure out on their own if they want to do that.

**Comment by jeremyboggs** [comment]
@elotroalex Though I'm totally open to being convinced otherwise. :smile:

**Comment by jeremyboggs** [comment]
I'd also say that merging the list of Neatline Exhibits with ExhibitBuilder's exhibits would be a separate issue from this one, if we in fact even agreed to explore that.

**Comment by davidmcclure** [comment]
@clioweb @elotroalex, There's already a public exhibits-browse view at `/neatline`. This can always be added as a navigation element, and then set as the home page. Although I agree that it would be nice if there were a somewhat more automagical/default way to do this.

**Comment by jeremyboggs** [comment]
You're right, @davidmcclure. You can just add the link to the navigation in Omeka Admin > Appearance > Navigation, add the link using '/neatline' as the URL. Save changes to save that link in the navigation list, then choose that link for the Homepage and save changes again. A bit of a clumsy process, but easy enough. Suggest we close this issue, since it's already possible to set the browse as the home page, and since this may not be what @elotroalex was wanting anyways.

**Comment by elotroalex** [comment]
I agree @davidmcclure, @clioweb. The navigation solution works. I did
prefer (a)  above anyway, which was to have the browse view be part of the
homepage, not the whole homepage. I imagine copying and pasting the PHP
from the browse view into the homepage of whatever theme would also do the
trick, am I mistaken?

**Comment by davidmcclure** [comment]
@elotroalex Yeah that would work. I'm hesitant to make really significant changes to the front page - adding a link is fine, but actually listing out the exhibits by default is probably a bit too intrusive.

Really this kind of thing - the process of creating the link to /neatline, setting it as the home page - is an ideal candidate for a sort of "Workflows and Guides" type of documentation that I've been hoping to add for a while. The idea would be to break out a separate section of the docs (imagine another top-level header like "[Reference Documentation](https://github.com/scholarslab/Neatline/wiki)") for little walk-throughs with step-by-step instructions for how to do specific, focused tasks. Eg:
- Make the Neatline exhibits browse view the home page of the site.
- Set up Omeka/NL on MAMP.
- Install Geoserver on AWS.
- etc.

Either of you want to take a crack at writing a little tutorial for this? I'd think a couple hundred words should do it.

**Comment by elotroalex** [comment]
I love your idea, @davidmcclure! This would be a perfect "exercise." I
might be doing some development on a Neatline project in a couple of weeks,
maybe I'll whip this one out. Stay tuned.

**Comment by jeremyboggs** [comment]
Depending on which version of Neatline you're using, @elotroalex, you could display a list of Neatline exhibits on your home page along with all your other stuff. This would be a reason to reopen this ticket, and provide an option to display a list of recent Neatline exhibits on the home page, along with recent items, collections, etc. There's a hook on the home page to do that.

Writing up a tutorial on how to do that, though, would be pretty useful, and shouldn't be too hard to actually do. I could write that up fairly quickly and post to the Neatline and Scholars' Lab blogs.

**Comment by elotroalex** [comment]
It used to do it in the old version. Yes, @clioweb I like the option on the
interface to hook to the homepage. I just didn't want to add to the pile
when there was a solution that could be solved with what we have. A
tutorial on the blog post would be fantastic and I know people who could
use that know-how right away.
