### ISSUE TITLE
Items Query always returns zero items

### ISSUE THREAD

**Issue by damonbla** [scholarslab/Neatline#215]
I'm using Omeka 1.5.3 and Neatline 1.1.2 just on my local machine to play around with it.  I'm running Mac OS X 10.8.3 with the usual MAMP setup.

I have multiple Items uploaded to Omeka - a couple with some images and one with a pdf.  I added them all to a collection.  I created a Neatline exhibit, but no items will ever show up in it, no matter what query I try.  Keywords, range of ids, choosing the collection name, type, tags - none of them will work.  If I do a regular advanced search, my items show up.  In my Neatline exhibit however, nothing ever returns with the queries, and my exhibit always has 0 items.

Could I possibly be doing something wrong?  Do I need another version of something?  Thank you for any help!

**Comment by davidmcclure** [comment]
Hi damonbla - Hmm, not sure what this might be. Keep in mind that all of the options on the form are `AND`-ed together, not `OR`-ed, meaning that entering multiple parameters could have the effect of narrowing down the set of results to 0.

Try this - enter "1-100" in the "Range" input and clear all the other inputs. Click "Search," and then open up the exhibit editor by clicking on "Edit" link on the listing for the exhibit.

Do you see any items listed in the left pane?

**Comment by damonbla** [comment]
Thank you for the reply!  Unfortunately, that did not work - there are no items listed.  # Items still says 0 in the omeka admin, and when I click on Edit, all I get is the top bar of Neatline, and none of the buttons or links will do anything.  Here are some screenshots, and hopefully you'll be able to see them:

My items in Omeka itself: http://www.damoweb.com/images/omeka-items.jpg
The Exhibit in Neatline: http://www.damoweb.com/images/neatline-exhibit.jpg
The Neatline query: http://www.damoweb.com/images/neatline-query.jpg
The Neatline edit screen: http://www.damoweb.com/images/neatline-edit.jpg

**Comment by davidmcclure** [comment]
Ah - the problem here isn't actually the item import, it's that you're using an older version of the plugin (1.1.2) that was broken by an external API change a couple weeks ago.

[Upgrading to 1.1.3](http://omeka.org/add-ons/plugins/neatline/) should fix the problem. Also, if possible, I'd recommend going ahead and installing Omeka 2.0 and using the [Neatline 2.0-alpha2](http://www.scholarslab.org/geospatial-and-temporal/announcing-neatline-2-0-alpha2/), which is the most up-to-date version of the plugin.

**Comment by damonbla** [comment]
That fixed it!  Thank you so much David!
