### ISSUE TITLE
Documentation: "Preparing to Install"

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#217]

**Comment by davidmcclure** [comment]
Hm, actually, this section may be extraneous - Wayne's [installation docs](https://github.com/scholarslab/Neatline/blob/feature/docs/docs/final/installing-neatline.md) pretty much cover what I was imaging here. What do you think?

**Comment by erochest** [comment]
Agreed. I was coming up with content for this, but it was a bit thin.

I'll delete the file and close the issue.
