### ISSUE TITLE
Add the ability to change heights and widths of all display blocks

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#23]
The administrator should be able to change the relative heights and widths of all display elements (map, timeline, undated) by just clicking and dragging on handles, like how the item editor width works now.

**Comment by waynegraham** [comment]
In the admin section, have the ability to toggle menus on, and off, allowing user to focus on the specific element they are wanting to view. Use case is someone wanting to view only the map, be able to just see that element of the Neatline.

**Comment by davidmcclure** [comment]
Done.
