### ISSUE TITLE
More detail in docs for Neatline and SIMILE.

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#246]
Docs should indicate that you need to select the SIMILE widget under the "Style" heading if you wish for the item to appear on the timeline. Simply filling out the date fields won't cause the items to appear on the timeline.

**Comment by csbailey5t** [comment]
Duplicate.

**Comment by jeremyboggs** [comment]
> Duplicate.

@csbailey5t Of which ticket?

**Comment by jeremyboggs** [comment]
@csbailey5t Nevermind. I really should learn to read.
