### ISSUE TITLE
Permissions and links in admin interface

### ISSUE THREAD

**Issue by erochest** [scholarslab/Neatline#248]
If contributors or researchers go to /admin/neatline, they can click on the link to edit the Neatline Exhibit (although it just goes to a 403 page). The link should not be created if the user doesn't have permissions to access the link's target page.

**Comment by davidmcclure** [comment]
Thanks for fixing this, although it seems that the change is causing test failures.

**Comment by jeremyboggs** [comment]
Fixed in a699271f8c77af312be0683a781f68a2399d74d6.
