### ISSUE TITLE
Unexpected behavior-Save button in full screen text editor

### ISSUE THREAD

**Issue by rondauva** [scholarslab/Neatline#250]
When the full screen text editor is opened and content is added, clicking the Save button does not save the content in the editor window, and if the record has not been previously saved, the content is does not appear in the Body dialog box.

Clicking the Minimize button does result in the contents of the editor appearing in the Body dialog box.

When content already in the Body dialog box is opened in the full screen editor, clicking the Save button does not save any changes made to the contents in the editor. Clicking the Minimize button does save changes made.

**Comment by davidmcclure** [comment]
Yep, this is super confusing, closing as a duplicate of #232.
