### ISSUE TITLE
Map offset between OSM and Google Maps

### ISSUE THREAD

**Issue by martiniusDE** [scholarslab/Neatline#254]
Hello,

I tried the new version 2.1.0 (environment: XAMPP, Omeka 2.1.1 and Windows XP). The previous version 2.0.4 works fine. But now I have a different view of geographic items on a google and a openstreet map (see attached pictures). The points are in different locations, the openstreet-map has the correct alignment. Besides, it seems to be a issue with the zoom, because the points are in different positions in various zoom factors on the map of google.

Greetz,
Martinius

![neatline_2 1 0_googlemaps](https://f.cloud.github.com/assets/2302200/1189955/6bf58fa6-2428-11e3-8085-c9d014e2a84a.jpg)
![neatline_2 1 0_osm](https://f.cloud.github.com/assets/2302200/1189956/6c21efa6-2428-11e3-88e3-6f0668ceb56b.jpg)

**Comment by martiniusDE** [comment]
Actually, the problem appears only in the new fullscreen view by all map types from google maps service. The other views (normal ormeka public view and the neatline editor) showing the google maps correct.

I hope this helps

**Comment by davidmcclure** [comment]
Hmm, interesting - thanks for posting this. I suspect this is some kind of weird interaction between the Google API and the method we use to do the fullscreen exhibits. I'll investigate today and fix before pushing out a public release of 2.1.

Thanks again!
-David

**Comment by davidmcclure** [comment]
Hey martiniusDe,

I just pushed a change to the `develop` branch that I believe fixes this problem. Could you pull the changes and let me know if it resolves the issue for you?

Thanks!

**Comment by davidmcclure** [comment]
Fixed by 8525fc9b897cf95cc8d13f00938d991c8234347d.
