### ISSUE TITLE
Add a "neatline" class to body tags of themed pages

### ISSUE THREAD

**Issue by zachwhalen** [scholarslab/Neatline#255]
First of all, Neatline is great!

However. I'd like to change its appearance. I'm happy to do that with CSS, but that would be much more straightforward if a themed page displaying a Neatline exhibit would add a "neatline" class (or something) to the <body> tag. 

This would make it consistent with what a Simple Page or an Item Views page does.

I imagine this would be pretty easy, but since I haven't yet figured out how to hack it in I thought I'd post it as a suggestion here.

Zach

**Comment by davidmcclure** [comment]
Hey Zach - Indeed! We actually do this in themes we use with Neatline, but it wasn't in the default templates in the plugin. Thanks for bringing this to my attention - I just pushed a fix (59ed5cf16a8393e8f016afe3cf0b7f2940de3e03). 

I'll include this with a point release next week (or if you're working the the git repository, you can just pull it now).

**Comment by zachwhalen** [comment]
Cool, thanks. Also, is fullscreen view new for 2.1.0!? That's basically what I was going to do with my CSS intervention anyway, but if you've already got it!

**Comment by davidmcclure** [comment]
Hey Zach - yep, 2.1.0 has a fullscreen mode! Thanks for bringing this up anyway, though, those CSS classes should be there regardless.
