### ISSUE TITLE
ACLs for Viewing Exhibits

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#257]
This has to do with the 2.1 release of Neatline:

When a user with "Contributor" permissions can see a list of Neatline exhibits in the admin panel, but when they click on the "full-screen" view, get a 403 error.

When a user with "Researcher" permissions logs in, they do not see any exhibits, but are presented with an option to create a new Neatline exhibit. When they click on this button, they get a 304 error.

Admin and super permissions are operating as expected.

**Comment by waynegraham** [comment]
Just a short follow up, the "Public View" path works as expected for "Contributor" roll.

**Comment by davidmcclure** [comment]
Fixed by cb818c5f02d97e4f5ee3a35385942304915ab58b.
