### ISSUE TITLE
Error saving records in Neatline editor

### ISSUE THREAD

**Issue by zachwhalen** [scholarslab/Neatline#258]
Hi,

I've got several student teams working on Neatline exhibits, and all but one have run into the same problem. 

Create a new record in neatline, save it, success!
Edit that item, save it again, and "There was an error; the record was not saved."

I haven't been able to reproduce this in my own Omeka installations, but I've accessed theirs and confirmed that they really are getting this error message. 

Pulling up the javascript error console revealed two interesting messages. At first, it says 

> Failed to load resource: the server responded with a status of 404 (Not Found)

with the URL in question being of a construction like 

> http://www...pathtoOmeka.../neatline/records/9

Browsing to that URL in question does actually yield a page of what looks like a JSON-packed version of the HTML used for the Static bubble display related to that resources.

Saving again yields a different console error:

> PUT http://www...pathtoOmeka.../neatline/records/9 404 (Not Found) 

and that identifies neatline-editor.js:3 as the location of the error.

As I said, I can't reproduce the error on my own server, and I'm at a loss trying to isolate differences between my installation and theirs that might create this sort of problem. Any ideas?

Zach

**Comment by davidmcclure** [comment]
Hey Zach,

Hmm, odd, I don't think I've seen this before. What version of Neatline are they using? Let's try this:
1. Open up one of the exhibits with the problem in Chrome. Open the Developer Tools, and click over to the "Network" tab.
2. Create a new record, save it, then try to save again, triggering the error. Down in the Network tab, you should see two new requests - one labelled with the integer ID of the record (say, `50`), and another request with a set of complex parameters, like `neatline/records?extent=POLYGON((-14971301.541763+3962400.....`.
3. Click on the listing for the first of the two requests. A new panel should open up to the right. Click the "Response" tab, and paste in the contents.

That should help us debug. Thanks!

**Comment by zachwhalen** [comment]
Hi David,

Thanks for the quick response. Following your directions, I did learn something significant. It's not worth pasting here, though, because I recognized the response on the first student site I tried was in fact a Drupal 404 page. On the second site I tried, it was WordPress. 

These are students who have Drupal or WP installed at the top of their domains with Omeka living in a subdirectory, so it looks like the paths have gotten crossed somewhere.

So, then, the problem may yet lie deeper than Neatline. At the same time, though, regular Omeka items save and edit just fine in the dashboard, so does Neatline interact differently with .htaccess rules?

I did have to help another student regain access to her site after the cPanel file manager ate her main Omeka .htaccess file, so could it be the same kind of routing problem within Neatline?

Thanks,
Zach

**Comment by davidmcclure** [comment]
Yeah, I can't think of a reason offhand why Neatline would react differently than the rest of Omeka. In the DevTools, in the details view for the problem request, click over to the "Headers" tab - can you paste in the first three keys? Should look something like this:

```
Request URL:http://localhost:8888/labs/neatline/records/3666
Request Method:PUT
Status Code:200 OK
```

**Comment by waynegraham** [comment]
@zachwhalen I've seen some weird stuff with Apache configurations that get installed by cPanel installations of Drupal and Wordpress. It's a bit of a tough situation to debug because there are some areas that trickle down to the `.htaccess`, and others that are over-ridden by the actual httpd configuration that gets written. Do you by any chance have a copy of httpd configurations? Typically I've seen these in the `AllowOverride` statements...

**Comment by zachwhalen** [comment]
@davidmcclure Here's those first three lines from one of the sites (the Drupal one):

> Request URL:http://www.jackhylan.net/mapmydevice/neatline/records/11
> Request Method:PUT
> Status Code:404 Not Found

**Comment by zachwhalen** [comment]
@waynegraham It seems I don't have permission to read httpd.conf on this server, but I've sent an inquiry to someone who does.

**Comment by timmmmyboy** [comment]
Hey folks, I'm an admin for this server. [Here is the .htaccess file](http://pastebin.com/Tz1wKAxz) which should be the standard with Omeka installs. As far as our httpd.conf we have AllowOverride set to all. [This is the user-specific information](http://pastebin.com/icLjX8qu) for that install (which would probably be consistent with most users on the system). Let me know if there's any other troubleshooting or information I could provide.

**Comment by zachwhalen** [comment]
I've now reproduced the bug in my own account on the server my students are using, so I can use this account of mine to do some deeper testing. I'll update if I find anything out.

**Comment by zachwhalen** [comment]
It's not much, but I've found one way to make a small difference. When i have Omeka in a subdirectory (in this case, www.writingthroughmedia.net/omekatest/) I can get the error as described above.

When I have Omeka in the top of a subdomain, though (omekatest.writingthroughmedia.net), it's a little different. I can create a record and saving it the first time works fine.

Subsequent saves, however, report "The record was saved successfully!" and yet don't actually save the new changes to the record.

For one of those latter situations, here's the response output I got from Chrome:

Response header:

> Request URL:http://omekatest.writingthroughmedia.net/neatline/records/1
> Request Method:PUT
> Status Code:200 OK

Response content:

> {"owner_id":1,"item_id":null,"exhibit_id":1,"added":"2013-10-01 14:03:10","modified":"2013-10-01 02:03:10","is_coverage":0,"is_wms":0,"slug":null,"title":"adfae","body":"adfae","coverage":null,"tags":null,"widgets":null,"presenter":"StaticBubble","fill_color":"#00aeff","fill_color_select":"#00aeff","stroke_color":"#000000","stroke_color_select":"#000000","fill_opacity":"0.30","fill_opacity_select":"0.40","stroke_opacity":"0.90","stroke_opacity_select":"1.00","stroke_width":2,"point_radius":10,"zindex":null,"weight":null,"start_date":null,"end_date":null,"after_date":null,"before_date":null,"point_image":null,"wms_address":null,"wms_layers":null,"min_zoom":null,"max_zoom":null,"map_zoom":null,"map_focus":null,"id":1}

I also noticed that the request cookie on my non-working sites looks different than it does for my site where everything works just fine.

Working site request cookie:

> SESSf4919bd70dbbf0ec66c6610579d36f9c=FBqk9JLuKFRpegof-Cuwmi7pfqqVMcbRhfIrw1sWxok; SESS4834703efdb10f502ac1594437e9f99c=8da88fb65ab4ab8953a786641a9028ce; SESSeddd6b0c178983edd6d83bc4836a600c=8a9f950995c4cbfa8a07f0eeffa06352; __utma=250405901.1869626511.1377542796.1380133123.1380567097.12; __utmz=250405901.1380567097.12.2.utmcsr=t.co|utmccn=(referral)|utmcmd=referral|utmcct=/lSfYO1O7A5; cec072045fd12149b4d38fb920847a85=d3487a34e087624b01c3f2d6c5855ade

Not-working site request cookie:

> SESS70099f829b1f541bcb9c6fa4dda6c21f=HltR5GiS3v8kVH-xzcb0TKLp-U_bgID1BozDeUuLkJo; 9899ca36085ae96ae212542a9258400c=27982661f39430f18e3e82b068c57441

I don't know if that's important or not, but I thought it worth mentioning.

Zach

**Comment by zachwhalen** [comment]
And yet another difference: the working site uses MySQL 5.1.70, non-working site runs MySQL 5.5.32 .

Both are at PHP 5.4.17, and all other plugin and Omeka versions are current.

And In terms of PHP extensions, the broken site has many more than the working site. The only one on the working site that is NOT on the broken site is APC.

**Comment by waynegraham** [comment]
@zachwhalen what does your .htaccess file for http://www.writingthroughmedia.net/ look like? The httpd configuration looks pretty stock for these things...

**Comment by waynegraham** [comment]
@zachwhalen I'm also getting intermittent network errors hitting the omekatest site (specifically loading the neatline-public.js file on the break-it exhibit). Is there any reported networking issues going on with the hosting provider?

**Comment by waynegraham** [comment]
@zachwhalen one more question, what browser(s) are you using?

**Comment by zachwhalen** [comment]
@waynegraham Here's the (Drupal generated) <a href="http://pastebin.com/LyDJ1PCa">.htaccess file</a> for writingthroughmedia.net, and <a href="http://pastebin.com/jcK1zfVy">here's .htaccess for the omekatest subdomain</a> in that account. 

I'm not aware of any network issues. @timmmmyboy may know more?

And I'm currently using Chrome on Ubuntu. My students yesterday were using the standard array -- IE, FireFox, Chrome. Maybe even one or two on Safari. It didn't seem to affect the non-editable-records behavior. All of their Omeka's are in subdirectories, thus triggering the first version of the bug I described above.

**Comment by timmmmyboy** [comment]
No network issues that I'm aware of, this server has very low load. I'm curious though why you're seeing two different MySQL versions reported @zachwhalen. writingthroughmedia is on UMW Domains, yes? Or were you referring to a test you were doing on a different domain?

**Comment by zachwhalen** [comment]
@timmmmyboy Yes, writingthroughmedia is on UMWDomains. I'm comparing it with the working site mapmyatari.zachwhalen.net, which is on hippie hosting.

**Comment by timmmmyboy** [comment]
Ah ok, that makes more sense then. I'd actually have guessed more network issues on Hippie Hosting than UMW Domains, the load is very different there. Happy to troubleshoot more since I'm an admin on both (the setup is quite similar between the two though).

**Comment by zachwhalen** [comment]
By the way, I'd be happy to give anyone who wants one a super user account on this broken site. Just let me know.

**Comment by waynegraham** [comment]
@zachwhalen On the Drupal side, I believe you need to change the `RewriteBase` to match the directory. For your writingthroughmedia site, it should look something like this in your Omeka .htaccess file:

```
RewriteBase /omekatest/
```

You may also want to update the caching directives in the .htaccess since this is a production site:

```
<IfModule mod_expires.c>
    <FilesMatch "\.(js|ico|gif|jpg|png|css)$">
        ExpiresActive on
        ExpiresDefault "access plus 10 day"
    </FilesMatch>
</IfModule>
```

This can help with allowing browsers to cache assets, and _hopefully_ mitigate some of the issues of the JavaScript not loading. 

Give this a try and let us know what happens...

**Comment by zachwhalen** [comment]
@waynegraham Thanks for the suggestions. I haven't tried the caching setting yet, but I can report no luck with RewriteBase. Changing it to /omekatest 500's out the site, I think because this currently lives in a subdomain, it's top level is "/" from the URL point of view. Setting it to 

```
RewriteBase / 
```

... so, just uncommenting that line in .htaccess, kept the site running but didn't change record-non-saving behavior.

Your suggestion makes sense for subdirectory installations, though. I'll be meeting with my students in a little while, so I'll get some of them to try it and see what happens.

**Comment by waynegraham** [comment]
@zachwhalen I should have been more clear, that is only for the issue when it's in a directory inside another application that has its own `.htaccess`. Virtual hosts will need the default `RewriteBase` (which is `/`).

One other question, can your students perform other non-Neatline tasks with their installations?

**Comment by zachwhalen** [comment]
@waynegraham Yeah everything else seems fine. At least, in my installation that mirrors their server situation and replicates the bug, I can create and edit normal Omeka item records normally.

**Comment by zachwhalen** [comment]
Just another update: On @waynegraham 's suggestion, I tried out the develop branch (2.1.2) on this broken installation and I'm still getting the same behavior. I can create records, but subsequent edits disappear.

**Comment by waynegraham** [comment]
Just some more follow up on this ticket, it turns out there was a setting the Apache configs outside of the Neatline application that was causing this issue. Essentially the PUT method that is used to save a record was being rewritten as a GET request by the server, which would not allow the record to be saved.

**Comment by zachwhalen** [comment]
Thanks for your help Wayne and David. I'll update if we isolate the specific config setting that led to the GET/PUT confusion.

**Comment by timmmmyboy** [comment]
I was able to narrow down in the logs the specific Mod Security rule that
was breaking this. Here is the rule (which is a part of the default set of
ModSec rules):

SecRule REQUEST_FILENAME|ARGS|ARGS_NAMES
"(?:\b(?:(?:type\b\W_?\b(?:text\b\W_?\b(?:j(?:ava)?|ecma|vb)|application\b\W_?\bx-(?:java|vb))script|c(?:opyparentfolder|reatetextrange)|get(?:special|parent)folder|iframe\b.{0,100}?\bsrc)\b|on(?:(?:mo(?:use(?:o(?:ver|ut)|down|move|up)|ve)|key(?:press|down|up)|c(?:hange|lick)|s(?:elec|ubmi)t|(?:un)?load|dragdrop|resize|focus|blur)\b\W_?=|abort\b)|(?:l(?:owsrc\b\W_?\b(?:(?:java|vb)script|shell|http)|ivescript)|(?:href|url)\b\W_?\b(?:(?:java|vb)script|shell)|background-image|mocha):|s(?:(?:tyle\b\W_=._\bexpression\b\W_|ettimeout\b\W_?)(|rc\b\W_?\b(?:(?:java|vb)script|shell|http):)|a(?:ctivexobject\b|lert\b\W_?(|sfunction:))|<(?:(?:body\b._?\b(?:backgroun|onloa)d|input\b._?\btype\b\W*?\bimage)\b|
?(?:(?:script|meta)\b|iframe)|![cdata[)|(?:.(?:(?:execscrip|addimpor)t|(?:fromcharcod|cooki)e|innerhtml)|\@import)\b)"
\

"phase:2,capture,t:none,t:htmlEntityDecode,t:compressWhiteSpace,t:lowercase,ctl:auditLogParts=+E,log,auditlog,msg:'Cross-site
Scripting (XSS)
Attack',id:'1234123404',tag:'WEB_ATTACK/XSS',logdata:'%{TX.0}',severity:'2'"

The file that is flagging this is /misc/jquery.cookie.js

I don't know enough about ModSecurity to understand exactly what it's
flagging but figured this would be helpful information. I'm going to remove
this rule from our server but as I mentioned this is a part of the default
configuration for Mod Security so it's possible there are other hosts that
have this rule enabled.

**Comment by waynegraham** [comment]
Apparently this is an issue (there's a closed ticket https://www.modsecurity.org/tracker/browse/CORERULES-31), which seems to come up for CPanel users. If you look If you look at the log file, you may be able to find the exact rule and filter it out with the  `SecRuleRemoveById` directive in the `.htaccess` file.

The curious thing is that I don't believe we're using `jquery.cookie.js` for anything...

**Comment by timmmmyboy** [comment]
Given that ticket mentions Drupal it looks like I was seeing the error from Drupal installs and falsely thinking it was the flag for the Neatline action. Looking at the folder for the user account in question that appears to be the case. I'll keep digging on which rule is causing problems with Neatline in particular. I'm sure it's somewhere in this massive error_log
