### ISSUE TITLE
Neatline WKT import

### ISSUE THREAD

**Issue by tamielbr** [scholarslab/Neatline#260]
I commented this on issue https://github.com/scholarslab/Neatline/issues/148, but I'm not sure that was correct (it was closed).  I have just tried importing POINT() data through Neatline Omeka (2.0.2) and it did not work. I added an item an included WKT data in the Coverage field (see image). I tried with and without quotes. When I import the item into Neatline the "Geometry (Well-Known Text)" the field always comes out empty. The item and other info imports correctly though.
![c534aa46-3041-11e3-911d-c3b3a7319e43](https://f.cloud.github.com/assets/3904166/1328618/7c9466be-3505-11e3-8dc8-49cd9f839a90.png)

**Comment by davidmcclure** [comment]
Hey tamielbr,

Thanks for getting in touch! You're right - Neatline currently won't import a plain-text "Coverage" value from Omeka. What it will do, though, is import any vector geometry created using the Neatline Features plugin, which lets you sketch out shapes on an interactive map directly inside the item edit form.

That said, Neatline logically should also pull in a raw coverage value. This should be a quick fix - I'll add it in and push out the change in the next point release.

**Comment by tamielbr** [comment]
Thanks - it does help, since we're working with a couple hundred data points through CSV plugin. Cheers.

**Comment by davidmcclure** [comment]
This is implemented in v2.2, due out early next week.
