### ISSUE TITLE
i18n updates

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#261]
Seems like there has been a few changes to various strings in Neatline, but the translations have not been updated in a year. We should generate a new translation file, push that up to Transifex, and hopefully get some translations for new strings.

**Comment by tamielbr** [comment]
I am hoping to begin translation to pt_BR soon, when this is up can you let me know? I'm already part of the pt_BR omeka translation group.

**Comment by jeremyboggs** [comment]
@tamielbr we just pushed up the new strings to Transifex. Thanks for helping!

**Comment by jeremyboggs** [comment]
Updated POT file in c1689f3f4b1f3017f495f5f535f6050d2c59e465.
