### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by tamielbr** [scholarslab/Neatline#263]
The "Editing Visibility" is broken.
I also noticed that there is information regarding the "Neatline Narrative" plugin which I can't find the the Omeka site. I am wondering what substituted this fuctionality?

I hope this is the right place to notify this!

**Comment by davidmcclure** [comment]
Hey tamielbr, thanks for catching this! There was a typo in the name of the source markdown file that was causing the link to break. Fixed: http://docs.neatline.org/style-tab-visibility.html.

As for the old Neatline Narrative plugin - that's actually called Neatline Text, now, and the code hasn't actually been publicly released yet. We're hoping to do that really soon, in the next couple weeks. For now, if you want to experiment, the source code is at https://github.com/scholarslab/nl-widget-Text - although, for the time being, there's no documentation, and we won't be able to provide support for it until we cut off an official release.

Best,
David

**Comment by tamielbr** [comment]
Tested it and it already works - awesome. I'll keep an eye for the next updated. Thanks!
