### ISSUE TITLE
Add "tiled=true" parameter to GetMap requests

### ISSUE THREAD

**Issue by mbertrand** [scholarslab/Neatline#265]
With some WMS map services (such as GeoServer with Geowebcache enabled), a parameter of tiled=true sent with a GetMap request will return cached tiles (if any) instead of generating the tiles on-the-fly.

**Comment by davidmcclure** [comment]
Hey @mbertrand - thanks for bringing this to our attention! I'll drop this in and push out the change with the next point release.

**Comment by davidmcclure** [comment]
Added.
