### ISSUE TITLE
Item ID field shouldn't be editable

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#267]
The Item ID field for a Neatline record is currently a text field where users can add an item ID to pull in data from that Omeka Item. After that Neatline record is created, and data is pulled in, users can still edit that Item ID field to change the ID to something else, and essentially compromise the relationship between the Neatline record on the map and the Omeka archive.

Right now you can also put in any number and it saves, regardless of whether there's an Omeka item with that ID.

**Comment by davidmcclure** [comment]
Fixed in 2.2.
