### ISSUE TITLE
Document how to add a record to the Timeline/Waypoints

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#269]
There's no documentation anywhere to point folks to how to do this...

**Comment by davidmcclure** [comment]
There are docs on the repos:

https://github.com/scholarslab/nl-widget-Simile#plotting-points-and-spans
https://github.com/scholarslab/nl-widget-Waypoints#adding-waypoints

And Simile-specific docs for Neatline's date fields:

http://docs.neatline.org/style-tab-dates.html

But we could definitely do a better job of linking it all together. Related to the neatline.org conversation?

**Comment by waynegraham** [comment]
It is, but came up in a support request (and I couldn't find it)

**Comment by jeremyboggs** [comment]
Related to or duplicate of #246.

**Comment by csbailey5t** [comment]
More broadly, we might want to create separate sections for Simile and Waypoints that provide an introduction to each plugin, followed by more specific instructions on adding items and changing options specific to each plugin.

**Comment by davidmcclure** [comment]
Looks like this has been added to http://docs.neatline.org.
