### ISSUE TITLE
neatline.org: Add plugins page to site

### ISSUE THREAD

**Issue by rondauva** [scholarslab/Neatline#275]
Consensus was to add a grid of plugins with shorter descriptions and smaller thumbnails. Also agreement not to list any that are wildly experimental that we're not willing to continue to develop.

**Comment by csbailey5t** [comment]
A plugin page listing Neatline, NeatlineText, NeatlineSimile, and NeatlineWaypoints was added in scholarslab/neatline.org@e85e0c9667537eb14e4d9ec4f76c91c67be940f3. Correct images were added in scholarslab/neatline.org@6d26f4ce6456bfab52de8514742e0ea5f1387e42
