### ISSUE TITLE
Problems with the new version with Waypoints

### ISSUE THREAD

**Issue by gabrielfedel** [scholarslab/Neatline#283]
Hi,
I update the Neatline to the last version (2.2.0), and some maps stopped work in edit mode.
This occur only the Waypoints plugin (the last version 2.0.2) is active.

Some idea of what the problem?

**Comment by davidmcclure** [comment]
Hey gabriel - did you upgrade Neatline Waypoints to 2.0.2? You'll need to do that in order for it to work with Neatline 2.2.0. Let me know if that solves the problem.

**Comment by gabrielfedel** [comment]
Hi David
yes! i updated, but this doesn't resolve =(

**Comment by davidmcclure** [comment]
Hmm, I can't replicate this, it's working fine on my end. Try this - in Chrome, open up the JavaScript Console (little three-bars icon at the top right of the screen > Tools > JavaScript Console) and then try to open the editor for one of the broken exhibits. Do you see any errors logged at the bottom of the screen? If so, could you paste them in here?

Thanks!

**Comment by gabrielfedel** [comment]
Hi David, 

a strange think happened, back to work with any chage!
i don't know why, but now it's working

thank you for help!

**Comment by davidmcclure** [comment]
Awesome - I bet you were getting a cached version of the old Javascript payload for Waypoints. Let me know if anything else comes up.
