### ISSUE TITLE
Problem importing uppercase P in Omeka Coverage into Neatline

### ISSUE THREAD

**Issue by tatumse** [scholarslab/Neatline#288]
Records with an uppercase P in the Omeka Coverage field don't import into Neatline. I tried three different installations of Omeka 2.1.4 with Neatline 2.2.1. A workaround is to import the record without the P and then add the P in Omeka after the import. After adding the P, sometime modifications to the Neatline record will save and sometimes they won't. I use an iMac with Safari. I tried a P in the Omeka Description field and had no problems.

**Comment by waynegraham** [comment]
Weird, so "POINT" fails in import; what happens if you wrap that in a GEOMETRYCOLLECTION()?

**Comment by tatumse** [comment]
To be more precise, the uppercase P does not import when it is the first letter of the first Coverage entry. Philadelphia does not import if it is the first entry. Chester, PA as the first entry, plus Philadelphia as the second entry does import.

**Comment by davidmcclure** [comment]
Bizarre. I suspect this line from the geoPHP library:

https://github.com/scholarslab/Neatline/blob/master/lib/geoPHP/geoPHP.inc#L266

I'll investigate tomorrow.
