### ISSUE TITLE
Make it possible to import raw WKT into an exhibit when Neatline Features is installed

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#299]
If Neatline Features is installed, Neatline will _only import coverages for items that were created using Neatline Features_ (see [here](https://github.com/scholarslab/Neatline/blob/cb15e23d618aff462ee248ef2bd511336d0babc9/models/NeatlineRecord.php#L258-270)). This means that regular, non-Features WKT strings in the Coverage element will be ignored.

This is unintuitive and unnecessary. The fix is easy - in `compileCoverage`, always set the raw value of the DC Coverage element first, and then check to see if Features is installed / try to suck up Features-specific WKT, which, if present, can take precedence over a regular, unadorned element text.

**Comment by davidmcclure** [comment]
Actually, after looking into this, now I remember why the code is the way it is. When Features is installed, trying to load the Coverage field using the `metadata` helper throws an error. So, this fails:

```
$coverage = metadata($item, array('Dublin Core', 'Coverage'));
```

To get around this, I made it an either-or proposition - if Features is installed, don't even attempt to get a regular Coverage value (since it will error), just look in the Features table.

@erochest, you have any idea how to get around this without doing major surgery on Features?

**Comment by erochest** [comment]
I'll have to look into this some to see exactly why it's failing. You're right, though. These two plugins should be able to work together in this way. I'll see what we can do about it.

**Comment by erochest** [comment]
This should take care of it. We'll try to wrap it up in a release in the morning.
