### ISSUE TITLE
Editor not working (white screen) with v2.2.2

### ISSUE THREAD

**Issue by krdyke** [scholarslab/Neatline#302]
Sorry for the SO type question, but after upgrading to v2.2.2, the editor is turning up blank white. I thought it was a conflict with some stuff I had done in 2.2.1, so I started with a fresh fork of 2.2.2, built it, created an exhibit, and still the white screen.

If it's just me, are there any likely culprits in the PHP code I should look at? I'm not seeing any JS errors, and a lot of the PHP templates are being added, just without anything in them (for example, an empty div with the editor id).

FYI, I'm running Omeka 2.1.4 on Ubuntu 12.10

Thanks for any help! Let me know if I can provide anything more concrete.

**Comment by waynegraham** [comment]
This is a confirmed bug that we discovered this morning and are currently working on a fix. We'll have this fixed ASAP. 

Just to confirm the status, if you create a new exhibit, can you see it on the public side?

**Comment by krdyke** [comment]
Yes, I should have mentioned that. I can view it on the public side with no
problem.

**Comment by waynegraham** [comment]
This is fixed in 62b20ed2f80fb273a64dabaf8808b68e163393aa There was a regression in the way Bower was resolving its dependencies for the editor.
