### ISSUE TITLE
Remove Files from zip file

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#303]
There are a lot of automation files included in the zip package that are not needed to actually run the software that we should remove to make this a smaller package.
- Gemfile.*
- Gruntfile
- assertions/
- bin/
- bower.json
- composer.*
- grunt
- package.json
- paths.json
- tests/

**Comment by erochest** [comment]
Most of these aren't currently included in our distribution package, although they're in the Github tagged download archive. I've gone ahead and removed the stuff from ckeditor, however.
