### ISSUE TITLE
Breaks jQuery on https

### ISSUE THREAD

**Issue by erochest** [scholarslab/Neatline#313]
On sites served with https, enabling Neatline appears to break Omeka's use of jQuery (the sliding "Save" box on the item edit page no longer slides).

**Comment by erochest** [comment]
This is actually a problem with Neatline and Fedora Connector both loading `bootstrap.js`. Perhaps it's a bug in Omeka? Either way, in the meantime, we'll prefix the file name.

**Comment by davidmcclure** [comment]
Weird, Javascript from Neatline shouldn't be getting loaded on the item edit pages at all...

**Comment by waynegraham** [comment]
@davidmcclure it appears as though Omeka loads the files to queue in the order the plugins are added to the database. What we observed is that when a plugin queues `bootstrap`, it's loading the last plugin that that satisfies this filename (and not the intended path). In the case where we ran in to this problem, it's FedoraConnector and Neatline. I think the easiest workaround is to prefix the bootstrap file with the plugin, though we're checking with @zerocrates too.

**Comment by davidmcclure** [comment]
Oh I see. Yeah, we could just rename to `neatline-bootstrap.js`, `fedora-bootstrap.js`, etc.

**Comment by zerocrates** [comment]
This is accurate. Omeka does just load stuff by making a stack of the various plugins, the current theme and the "global" stuff in application/views/scripts, and chooses the first thing it finds with the right name.

This works decently well in the directories for controllers and stuff (though there's some annoyances there also), but when you're in shared folders like css, javascripts, images, conflicts can arise pretty easily with generic names. Even in those situations, Omeka mostly makes it work by finagling the order of the stack so the current plugin's stuff gets loaded first, but that all falls apart when you're talking about stuff loaded onto another page with a hook.
