### ISSUE TITLE
Can not Import Omeka Items into Neatline

### ISSUE THREAD

**Issue by mcarring** [scholarslab/Neatline#316]
Hello, 

I'm using Omeka 
2.1.4 I'm getting this error message when trying to import Omeka items into a Neatline Exhibit

RuntimeException
The configured PHP path (/usr/bin/php) does not point to a PHP-CLI binary

Any ideas on how to fix this?

**Comment by waynegraham** [comment]
You can explicitly set the path for the PHP-CLI in the omeka settings. In `application/config/config.ini' change the`background.php.path`setting to the full path to php. You can tell what this is on the remote server with the`which` command.

```
$ which php
/usr/bin/php
```

In this case, you would set `background.php.path=/usr/local/php`. 

For more info on this particular issue, check out the Omeka forums (http://omeka.org/forums/topic/csv-import-problem-1).

**Comment by mcarring** [comment]
Hello, 

I am now getting a success message when I import items into Neatline and the Omeka items display in the drop-down menu in the Item section on the Neatline record. However, when I choose the Omeka item, Neatline gives me an error message and fails to load the Omeka item.  I am using Neatline 2.2.4 Any ideas? 

System Information 
Omeka   2.1.4
PHP 5.4.29 (cgi-fcgi)
OS  Linux 3.4.87-20140414.1.bh6.x86_64 x86_64
MySQL Server    5.5.37
MySQL Client    5.5.37
PHP Extensions
Regular bcmath, bz2, calendar, cgi-fcgi, Core, ctype, curl, date, dba, dom, enchant, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, odbc, openssl, pcntl, pcre, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, Reflection, session, shmop, SimpleXML, soap, sockets, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, Zend Guard Loader, zip, zlib
Zend    Zend Guard Loader

**Comment by davidmcclure** [comment]
Hey @mcarring - when exactly does Neatline display the error when you try to link a record to an item? Eg, is it when you type a search query in the box, when you select an item, when you save the Neatline record, etc?

**Comment by mcarring** [comment]
David, 

Thanks for replying. The error occurs when I try to save the Neatline record.

**Comment by davidmcclure** [comment]
Hey @mcarring,

Hm, strange, I'm not sure what's going on there. Let's try this:
1. In Chrome, open up the editor and go to the "Item" tab in the record form.
2. Open up the Developer Tools by clicking the little icon with three bars at the top right, then **Tools** > **Developer Tools**.
3. Click on the **Network** tab, and scroll to the bottom of the list.
4. Search for an item in the "Link to Omeka" box. Do accurate search results show up in the dropdown below the input? If so,
5. Click on one of the results. Does the metadata for the item appear in the blue box below the input?
6. Save the record, which should trigger the error. In the **Network** tab, you should see two new entries appear at the bottom of the list that look something like this, with different numbers:

```
1330
/labs/neatline/records
```

```
records?extent=POLYGON((-14968706.918204+3901657.7027932%2C-12229203.824844+3901657.7027932%2C-12229203.824844+5100190.306138%2C-14968706.918204+5100190.306138%2C-14968706.918204+3901657.7027932))&zoom=6&exhibit_id=28
/labs/neatline
```

And, assuming the error occurred, the first one should be red. Click on that request, and then click the **Response** tab in the sub-menu that shows up on the right. What's the value of the response?

Thanks,
David

**Comment by mcarring** [comment]
David, 

Thanks for your help on this. 
4. Accurate search results show up in the dropdown below the input. 
5. The metadata for the Omeka item appears in the blue box below the input. 

I got the first new entry which is 11
/omeka/neatline/records 
but did not get the second entry maybe because we are using a static image instead of a map? 

This is the error message I get when I click on the Response tab
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/home4/wclibrar/public_html/omeka/plugins/NeatlineFeatures/lib/NeatlineFeatures/Utils/View.php</b> on line <b>167</b><br />
<br />
<b>Fatal error</b>:  Call to a member function getText() on a non-object in <b>/home4/wclibrar/public_html/omeka/plugins/NeatlineFeatures/lib/NeatlineFeatures/Utils/View.php</b> on line <b>525</b><br />

![omekaimport](https://cloud.githubusercontent.com/assets/7989213/3449054/54b06c1e-0161-11e4-9e6b-dbf902f25980.png)

**Comment by waynegraham** [comment]
@mcarring can you try disabling the NeatlineFeatures plugin and try the import again?

Wayne

**Comment by mcarring** [comment]
Wayne, 

Disabling the Neatline Features plugin worked. I can now import and save Omeka items in Neatline. Any explanation for this?

Mary

**Comment by waynegraham** [comment]
I _think_ something got in the way of the NeatlineFeatures [setViewOptions](https://github.com/scholarslab/NeatlineFeatures/blob/master/lib/NeatlineFeatures/Utils/View.php#L161-170). 

@erochest Did this get fixed in that group of bugs you were working on, or is this a new one?

**Comment by erochest** [comment]
This hasn't been addressed in NeatlineFeatures. (I can replicate it, anyway.) I'm moving this issue over there. See scholarslab/NeatlineFeatures#86 for the rest of the story.

**Comment by erochest** [comment]
@mcarring , I've released a new version of NeatlineFeature (2.0.4). Could you try this and see if it takes care of your issue? Thanks

**Comment by mcarring** [comment]
Eric, 

I did not notice this post until today. Do you want me to turn on Neatline Features again after installing the new version?

**Comment by mcarring** [comment]
Is it best to download from http://neatline.org/plugins/neatline-features/ ?

**Comment by waynegraham** [comment]
@mcarring That page will take you the the Omeka plugins directory (http://omeka.org/add-ons/plugins/neatlinefeatures/) but it's the correct version.

**Comment by mcarring** [comment]
Wayne, 

I just tested the new version of the Neatline features plugin and I can import Omeka items and save the imported Omeka record with the Neatline features plugin activated. Thanks for your help on this issue.
