### ISSUE TITLE
Relation to Event in timeline

### ISSUE THREAD

**Issue by mcarring** [scholarslab/Neatline#319]
Hello, 
We would like to relate items in Omeka to a record in the Neatline timeline. The only way to do it that we can see is to use 
http://www.wc-library.org/omeka/neatline/show/timeline but this is not specific enough and does not generate a link for the user to the timeline. Is there a way of generating a link to a particular record such as record number 59 in the specific neatline timeline?

**Comment by waynegraham** [comment]
@davidmcclure will the new linking router enable this?

**Comment by davidmcclure** [comment]
Yes indeed! I'm doing the final release packaging for version 2.3 at this moment, which makes it possible to "hard link" to a given record. Eg, if a record has an ID of `16`, URLs like:

`http://www.wc-library.org/omeka/neatline/show/timeline#record/16`

Will automatically select that record when the page is loaded, just as if the user had manually clicked on the record for focus the exhibit.
