### ISSUE TITLE
Can't activate Records tab after clicking Plugins tab in Editor

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#321]
When I go into the exhibit editor, click the Plugins tab to do something with the plugins, I can no longer get back to the Records list. Clicking on the Records tab does nothing. I can, however, get to the Styles panel.

Tried on latest builds of Firefox and Chrome.

**Comment by waynegraham** [comment]
This _looks_ like the Record view isn't getting redrawn, but the Styles and  Plugins views are. @davidmcclure could this be related to the admin view controller? The URL does change when the anchor is selected, it's just not redrawing the view.

**Comment by davidmcclure** [comment]
Pull from develop, this was fixed in 2.3-rc2 by 644202a38ee8ef5e9491ff7c3ed5b82994ccbffd. Sorry about that - I had to change some of the routes in the editor to make them play nice with the new public record router, and forgot to change the `href` on that tab in the template.
