### ISSUE TITLE
Waypoints box fighting with Layer Selector popup 

### ISSUE THREAD

**Issue by jenbartle** [scholarslab/Neatline#327]
Hi--
When using the Waypoints widget, the Layer Selector popup box works as expected the first time only. After that, it is pushed behind the the Waypoints box and cannot be used again (it will open and close, but you cannot select a different layer a second time because the popup is pushed behind the Waypoints box.
[Omeka v.2.2.2;  Neatline v.2.3.0;  Neatline Waypoints v.2.0.2.]
Thanks!
Jen

**Comment by waynegraham** [comment]
I've moved this over to the Waypoints plugin (https://github.com/scholarslab/nl-widget-Waypoints/issues/3)...
