### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#39]
This needs tests...

**Comment by waynegraham** [comment]
Test coverage for PHP and Javascript needs to approach 100%

**Comment by davidmcclure** [comment]
Since we've decided to move away from the DC data storage and towards NL-specific tables for the text saves, we need to finalize the schema before we start testing.

**Comment by davidmcclure** [comment]
All application-critical PHP is tested as of 874e74797fcb66b7ebcb5acf6b014205d43f55cc.

**Comment by davidmcclure** [comment]
This is ongoing and not really an "issue."
