### ISSUE TITLE
Search ajax call should cancel running requests to avoid success overwrites

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#4]
When text is typed into the search box in the item browser, an ajax call is fired to fetch item results on keyup. In some situations when the latency hangs on one or another of the calls, you can have the situation when results populate for a completed word, but then one of the queries initiated by one of the previous keystrokes takes longer than the final query, returns null results, and overwrites the new list of results.

Each of these requests should cancel any other running requests to prevent this.

**Comment by waynegraham** [comment]
I have some concerns with ajax calls like this for large collections because of the way in which the ORM in Zend handles large queries (especially if you're using the getTable method). We need to deal with the issue for the SolrSearch plugin too.

**Comment by waynegraham** [comment]
Look at the abort() function.

**Comment by davidmcclure** [comment]
New version of item browser code irons this out.
