### ISSUE TITLE
Allow Neatline exhibit creation without an existing Map or Timeline

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#43]
If you try to create a Neatline exhibit without actually having an existing Map or Timeline in your database, you get the following error:

```
Before you can start a Neatline exhibit, create at least one map or one timeline.
```

Seems like you should still be able to create a Neatline exhibit without actually creating a separate timeline or uploading maps. You could just using any existing items, for example, and draw features on the base layer. Items themselves could also have date information that could appear on the Neatline exhibit's timeline.

If this isn't ideal, we should at least hide the create buttons until the user has the necessary Map and/or Timeline, with some explanation that they need to do that.

**Comment by davidmcclure** [comment]
Done.
