### ISSUE TITLE
Deprecation warnings, performance problem in Firefox

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#55]
There is some strange issue in the editor code that is (a) causing Chrome to throw huge numbers of console warnings and (b) Firefox to choke down to an incredibly slow pace, although Firebug does not log warnings/errors. I'm almost sure these are the same issue, because the elements on the page that throw the errors in Chrome are the same parts of the application that are anomalously slow in FF, whereas other parts perform as would be expected.

To replicate in Chrome:
- Move the mouse over the list of items in the browser, or interact with the layout editor dropdown box. This error: "event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future." gets thrown hundreds of times.

To replicate in Firefox:
- Open up an item form. The framerate drops _incredibly_ low. By comparison, click on the "Filter" tab and see the speed of the animation there. There is something specifically wrong in the browser code that is causing the slowdown.

**Comment by waynegraham** [comment]
Check the frame rate with stats.js (https://github.com/mrdoob/stats.js). May need to manually bump the frame rate (e.g. jQuery.fx.interval = 100;). I believe the default is 70 fps.

I did notice, however, that there are a lot (a lot ~= 31 for my 2 items) of ajax requests which will make the browser appear slower than it actually is as it's loading new info in to the DOM. 

May also need to take a look at ways to combine all of the different JavaScripts; I've been working on some code that will help, but we should sit down and make sure that the concatenation order is correct.

**Comment by davidmcclure** [comment]
In Omeka 1.4.2 with jQuery 1.7, the performance problems appear to be completely resolved. I'm pretty sure this is because jQuery 1.7 fixes the internal issue that was causing those strange, event.layerX/event.layerY warnings to get thrown.

I will make note of this in the documentation.
