### ISSUE TITLE
Installing on Omeka 1.4.2 / MAMP

### ISSUE THREAD

**Issue by gabrielhankins** [scholarslab/Neatline#56]
I'm attempting to install Neatline on a local virtual machine (MAMP) and am coming up with the following Omeka Admin error (in Firefox):
  The Neatline plugin cannot be loaded for the following reasons:

```
* Neatline requires the following plugins to be installed, activated, and loaded: "NeatlineMaps"
```

though I've got the plugin "Neatline Maps" installed.  Is this literally a problem with the spacing?

**Comment by davidmcclure** [comment]
NL doesn't require NLMaps anymore anyway, so I just got rid of the constraint.
