### ISSUE TITLE
Occasional window crash related to viewport defaults save

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#57]
Once in a while, hitting the "Fix Starting Viewport Positions" button in the layout configuration dropdown causes Chrome (perhaps other browsers too?) to freeze and then crash out of the tab. Usually, it works fine, and I can't reliably replicate it.

**Comment by waynegraham** [comment]
Sounds like a memory leak (and/or a lag in the AJAX requests). Don't happen to be using XPath expressions do you? There was an older bug with webkit that treated XPATH expressions that began with div as a binary operator (https://bugs.webkit.org/show_bug.cgi?id=50366). Could be a bug that has resurfaced.

**Comment by davidmcclure** [comment]
Yeah, that's the kind of problem that popped to mind. No XPATH anywhere in the vicinity. After further investigation, this is a truly, truly mysterious bug. I assumed that the problem was somehow tied to the events that get bound onto the button in the NL code; but even after totally removing the events, and even getting rid of the code that selects the markup on instantiation, the problem persists. And now it seems to happen all of the time.

**Comment by davidmcclure** [comment]
Fixed by 4e092b82f2b8e7c0259244778a5ee128a33cbc0b. The problem was isolated to the case where the timeline block was turned off, and when the NL code tried to get the focus date of the non-existent TL, things choked up. New code just checks to see if the TL is present and, if not, returns an empty string for the focus. 

(Apparently, when it seemed that the bug was still there even without the event bindings, I was seeing a cached version of the js file or something).
