### ISSUE TITLE
Add some explanation of our development process

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/Neatline#64]
To encourage collaboration with outside developers, we should add some explanation of our development process . Could simply be a listing of our major branches (master and develop) with description of each, and a link to [gitflow](http://nvie.com/posts/a-successful-git-branching-model/).

This could go on the README, though a wiki or project page might suffice.

**Comment by nowviskie** [comment]
Would be nice to do a version of this as a Scholar's Lab blog post, too.
