### ISSUE TITLE
Silent OpenLayers bug after new vector add

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#66]
There is a "silent" error that gets thrown in the editor after creating a new vector that, as far as I can tell, does not actually cause any undesirable behavior in the application, but nonetheless needs to be investigated, This been present for at least a couple months, and the cause is mysterious.

To replicate:
- Add a new vector (any context - Omeka record, NL-native record)
- Click save.
- Move the mouse over the map - OpenLayers will throw an error on each mousemove tick with a stack trace that contains no NL application code, just OL code.

**Comment by phybernightmare** [comment]
verify after new OL update

**Comment by erochest** [comment]
This appears to be fixed. Some Google Maps resources are being transfered with the wrong MIME type, but otherwise, I don't see anything.

I did harden this against null WKT's getting passed in, as that was causing a one-time exception. This is in 9745aca0ab04cf55c6a34d97ea4aacd0af36bacb.
