### ISSUE TITLE
CSS gradient bug in Safari on the ambiguity builder

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#67]
Safari does not render gradients correctly that contains markers at 0 or 100% (need to be 1 and 99, I believe). The CSS construction in the gradient builder uses 0 and 100, which causes a weird rendering bug in Safari.

Not super critical, since it doesn't hurt functionality (in Safari, as soon as you drag one of the sliders either way, the gradient renders correctly, and all's well from the start from a data standpoint).

But sloppy.

**Comment by erochest** [comment]
Works for me.

David, if this is still broken for you, re-open, and we'll talk about how to reproduce it. Thanks.
