### ISSUE TITLE
In-theme Neatline instantiation needs a container div resize listener

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#68]
Currently, the in-theme NL public views construct the NL inside of the theme container div, which may or may not be fixed or relative width. If the theme uses a percentage width for the container, resizing will cause the NL container to resize as well, and the current NL constructor code in that context does not listen for resize.

**Comment by davidmcclure** [comment]
Really, this is part and parcel with the public-facing exhibit views.

**Comment by jeremyboggs** [comment]
Related to #109.
