### ISSUE TITLE
Fast window resize breaks item browser horizontal dragging

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#8]
A quick / dramatic resize of the window can break the width sliding functionality of the item editor. Usually, after shrinking the size of the window quickly, the drag will still work in that state, but the dotted handle indicator will not display when the cursor hovers on the region. Then, if the window is dragged back open to a larger state, the drag will not work at all.

**Comment by waynegraham** [comment]
Did this get closed with the block assignment for styles?

**Comment by davidmcclure** [comment]
No, this bug is still present.

**Comment by davidmcclure** [comment]
Fixed.
