### ISSUE TITLE
Style.css loading bug

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#89]
Randomly, roughly 50% of the time, the style.css file for the OL theme does not load. It appears that OL is requesting the file locally, failing to load it, and then trying to load it remotely, which works some of the time but not always.

**Comment by phybernightmare** [comment]
verify this is still the case; fixed for Features in latest release

**Comment by waynegraham** [comment]
We believe this has been resolved with the upgrade to OpenLayers 2.12

**Comment by davidmcclure** [comment]
I can't replicate this with the upgraded OL. Closing this as fixed.
