### ISSUE TITLE
Map features do not reposition on map resize when the width is reduced 

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#96]
In all versions of Neatline, map feature vectors do not reposition with the map if the size of the map container div is reduced relative to the _starting position of the div on pageload_. To reproduce:
- Open a Neatline exhibit, in any context (editor, public view, edition, etc.)
- Drag the width of the window outwards. The map feature vectors will reposition correctly as the map widens.
- Drag the size back to the original width, and then continue to make the map smaller. The vectors will "stick" exactly at the position they were when the width passed through the original starting width.

**Comment by waynegraham** [comment]
May need to write an observer for window resizing;
$.resize(function() {
    var dim = document.viewport.getDimensions();
    map.div.setStyle({width:dim.width+'px', height:dim.height+'px'});
    map.size(dim.width, height)
    map.updateSize();
});

**Comment by davidmcclure** [comment]
Yep, this gets done, it's something else (see https://github.com/scholarslab/Neatline/blob/master/views/shared/javascripts/neatline_map.js#L976).

**Comment by nowviskie** [comment]
Not sure if this is related, but I lose the map and timeline entirely at certain dimensions when I'm resizing. It redraws fine in Chrome, but half the time when I'm resizing the window using Firefox, the whole neatline-container div stays white.

**Comment by phybernightmare** [comment]
This may be an OL bug; need more info

**Comment by phybernightmare** [comment]
verified this is an OL bug; fixed in 2.12 rc4+

**Comment by davidmcclure** [comment]
Fixed.
