### ISSUE TITLE
Delete data records when parent item is deleted

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#98]
When an Omeka item is deleted, any Neatline data records that are associated with that item should also be deleted. This does not happen now, and it causes major problems where there is an activated data record in an exhibit that is "marooned" when the parent item is removed.

**Comment by phybernightmare** [comment]
Look at the before_delete_record_hook

**Comment by erochest** [comment]
Fixed in b58f09ad91a26416489270955099845997b9e3e3
